xtimers-customer:
  db:
    mysql:
      url: jdbc:mysql://localhost:3306/xtimers-customer?serverTimezone=UTC
      user: root
      password:
    liquibase:
      enabled: true
      drop-first: true